server:
  port: 7777

spring:
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: admin
    password: my-password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db.logfile/master_file.yml